#!/usr/bin/env python3
"""Generate RGB565 Echo Pyramid status sprites from the Nous status sheet."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageOps


FRAME_NAMES = ("ASLEEP", "READY", "LISTENING", "THINKING", "SPEAKING", "ERROR")
SPRITE_SIZE = 128


def rgb565(pixel: tuple[int, int, int]) -> int:
    red, green, blue = pixel
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def crop_panel(sheet: Image.Image, index: int) -> Image.Image:
    panel_width = sheet.width // len(FRAME_NAMES)
    left = index * panel_width
    panel = sheet.crop((left, 0, left + panel_width, sheet.height)).convert("RGB")

    # Trim the generated panel border and outer whitespace while keeping the
    # state cue. The panel art is square-ish inside a taller generated canvas.
    inset_x = int(panel_width * 0.02)
    inset_y = int(sheet.height * 0.12)
    bottom_inset = int(sheet.height * 0.18)
    return panel.crop((inset_x, inset_y, panel_width - inset_x, sheet.height - bottom_inset))


def fit_sprite(panel: Image.Image) -> Image.Image:
    return ImageOps.fit(
        panel,
        (SPRITE_SIZE, SPRITE_SIZE),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )


def write_header(frames: list[Image.Image], output: Path) -> None:
    lines: list[str] = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Generated by firmware/echo-pyramid/tools/generate_status_sprites.py.",
        f"constexpr int kNousStatusSpriteWidth = {SPRITE_SIZE};",
        f"constexpr int kNousStatusSpriteHeight = {SPRITE_SIZE};",
        "constexpr int kNousStatusSpriteCount = 6;",
        "",
        "enum NousStatusSpriteIndex {",
    ]
    for index, name in enumerate(FRAME_NAMES):
        lines.append(f"  NOUS_STATUS_SPRITE_{name} = {index},")
    lines.extend(
        [
            "};",
            "",
            "static const uint16_t kNousStatusSprites[kNousStatusSpriteCount][kNousStatusSpriteWidth * kNousStatusSpriteHeight] = {",
        ]
    )

    for name, frame in zip(FRAME_NAMES, frames, strict=True):
        data = frame.convert("RGB").tobytes()
        pixels = [
            rgb565((data[index], data[index + 1], data[index + 2]))
            for index in range(0, len(data), 3)
        ]
        lines.append(f"  // {name}")
        lines.append("  {")
        for offset in range(0, len(pixels), 12):
            chunk = ", ".join(f"0x{value:04x}" for value in pixels[offset : offset + 12])
            suffix = "," if offset + 12 < len(pixels) else ""
            lines.append(f"    {chunk}{suffix}")
        lines.append("  },")

    lines.extend(["};", ""])
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sheet", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()

    sheet = Image.open(args.sheet).convert("RGB")
    frames = [fit_sprite(crop_panel(sheet, index)) for index in range(len(FRAME_NAMES))]
    args.header.parent.mkdir(parents=True, exist_ok=True)
    write_header(frames, args.header)

    if args.preview is not None:
        preview = Image.new("RGB", (SPRITE_SIZE * len(frames), SPRITE_SIZE), "white")
        for index, frame in enumerate(frames):
            preview.paste(frame, (index * SPRITE_SIZE, 0))
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        preview.save(args.preview)


if __name__ == "__main__":
    main()
