#pragma once

#include "esp_err.h"

#define LOG_TAG "hermes_iot_fw"
#define TICK_INTERVAL 20
#define MAX_HTTP_OUTPUT_BUFFER 2048
#define MAX_SIGNALING_SDP_BUFFER 8192

#define HERMES_IOT_WIFI_SSID CONFIG_HERMES_IOT_WIFI_SSID
#define HERMES_IOT_WIFI_PASSWORD CONFIG_HERMES_IOT_WIFI_PASSWORD
#define HERMES_IOT_GATEWAY_BASE_URL CONFIG_HERMES_IOT_GATEWAY_BASE_URL
#define HERMES_IOT_DEVICE_ID CONFIG_HERMES_IOT_DEVICE_ID
#define HERMES_IOT_FIRMWARE_VERSION CONFIG_HERMES_IOT_FIRMWARE_VERSION

extern esp_err_t hermes_init_wake_word(void);
